### ISSUE TITLE
SDK should support configurable Logger

### ISSUE THREAD

**Issue by theluk** [mixpanel/mixpanel-php#17]
There is currently no (common) way to change the debugging / logging mechanism. 
It would be convenient if we could define custom logging mechanism that is based on the widely used [Psr\Log\LoggerInterface](https://github.com/php-fig/log/blob/master/Psr/Log/LoggerInterface.php)

**Comment by jbwyme** [comment]
I'd love to see what you came up with for the custom consumers. In terms of logging I agree that the error_log isn't the best place for it and using the industry standard is the right way. I'm happy to take a look at any pull requests you have if you've already modified these things. Otherwise I'll queue them for us to work on them.
